sorted_interfaces: "{{ ansible_interfaces | sort }}"
win_sorted_interfaces: "{{ ansible_interfaces | map(attribute='connection_name') | sort }}"
networks: "{{ [network] + extra_networks | default([]) }}"
